name: agatra
description: A new Flutter project.
publish_to: 'none'
version: 0.0.4

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  flutter_secure_storage: ^9.0.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.2
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/
